import Anthropic from "@anthropic-ai/sdk";
import { config } from "../config/index.js";

const anthropic = config.ANTHROPIC_API_KEY
  ? new Anthropic({ apiKey: config.ANTHROPIC_API_KEY })
  : null;

/**
 * Check if an app name looks like a random cute name (adjective-animal-verb pattern)
 * These are generated by generateCuteAppName() and should be replaced with AI-generated names
 */
export function isRandomAppName(name: string): boolean {
  // Pattern: lowercase-word-word-word (e.g., "happy-fox-run", "gentle-panda-hop")
  const pattern = /^[a-z]+-[a-z]+-[a-z]+$/;
  return pattern.test(name);
}

/**
 * Generate a short, descriptive name for an app based on the user's first message
 */
export async function generateAppName(userPrompt: string): Promise<string | null> {
  console.log("[TitleGenerator] Generating app name for prompt:", userPrompt.slice(0, 100));

  if (!anthropic) {
    console.warn("[TitleGenerator] No Anthropic API key configured");
    return null;
  }

  try {
    console.log("[TitleGenerator] Calling Anthropic API for app name...");
    const response = await anthropic.messages.create({
      model: "claude-3-5-haiku-20241022",
      max_tokens: 50,
      messages: [
        {
          role: "user",
          content: `Generate a very short app name (2-4 words max) that describes what this app will do. Return ONLY the name, no quotes, no punctuation. Use Title Case.

User's request: "${userPrompt.slice(0, 500)}"`,
        },
      ],
    });

    const name =
      response.content[0].type === "text"
        ? response.content[0].text.trim()
        : null;

    if (!name) {
      return null;
    }

    console.log("[TitleGenerator] Generated app name:", name);

    // Ensure name is not too long
    return name.length > 50 ? name.slice(0, 47) + "..." : name;
  } catch (error: any) {
    console.error("[TitleGenerator] Failed to generate app name:", error?.message || error);
    return null;
  }
}

/**
 * Generate a short, descriptive title for a chat based on the user's first message
 */
export async function generateChatTitle(userPrompt: string): Promise<string> {
  console.log("[TitleGenerator] Generating title for prompt:", userPrompt.slice(0, 100));

  if (!anthropic) {
    console.warn("[TitleGenerator] No Anthropic API key configured");
    return "New Chat";
  }

  try {
    console.log("[TitleGenerator] Calling Anthropic API...");
    const response = await anthropic.messages.create({
      model: "claude-3-5-haiku-20241022",
      max_tokens: 50,
      messages: [
        {
          role: "user",
          content: `Generate a very short title (3-6 words max) for a chat that starts with this message. Return ONLY the title, no quotes or punctuation at the end.

User message: "${userPrompt.slice(0, 500)}"`,
        },
      ],
    });

    const title =
      response.content[0].type === "text"
        ? response.content[0].text.trim()
        : "New Chat";

    console.log("[TitleGenerator] Generated title:", title);

    // Ensure title is not too long
    return title.length > 60 ? title.slice(0, 57) + "..." : title;
  } catch (error: any) {
    console.error("[TitleGenerator] Failed to generate title:", error?.message || error);
    return "New Chat";
  }
}
