apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kova-app.name" . }}-workspace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kova-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
